blog_dir: blog
domain: http://nqis.org
exclude: "*.sass, *.scss, Gemfile, Gemfile.lock, Procfile, README.md, *.rb, *.yml, bin"
lsi: true
markdown: rdiscount
paginate: 10
permalink: /blog/:year/:month/:day/:title
pygments: true
